//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_2016.ServiceReferenceProyecto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProyecto.WebServiceProyectoSoap")]
    public interface WebServiceProyectoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponse HelloWorld(Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponse> HelloWorldAsync(Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceProyectoSoapChannel : Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceProyectoSoapClient : System.ServiceModel.ClientBase<Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap>, Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap {
        
        public WebServiceProyectoSoapClient() {
        }
        
        public WebServiceProyectoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceProyectoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProyectoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceProyectoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponse Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap.HelloWorld(Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest inValue = new Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest();
            inValue.Body = new Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequestBody();
            Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponse retVal = ((Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponse> Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap.HelloWorldAsync(Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proyecto_2016.ServiceReferenceProyecto.HelloWorldResponse> HelloWorldAsync() {
            Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest inValue = new Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequest();
            inValue.Body = new Proyecto_2016.ServiceReferenceProyecto.HelloWorldRequestBody();
            return ((Proyecto_2016.ServiceReferenceProyecto.WebServiceProyectoSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
